/*
SQLyog Ultimate v12.09 (64 bit)
MySQL - 10.1.19-MariaDB : Database - db_sigula
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `t_lap_harian_pengolahan_ptpn` */

DROP TABLE IF EXISTS `t_lap_harian_pengolahan_ptpn`;

CREATE TABLE `t_lap_harian_pengolahan_ptpn` (
  `id` int(50) NOT NULL AUTO_INCREMENT,
  `company_code` varchar(4) DEFAULT NULL,
  `plant_code` varchar(4) DEFAULT NULL,
  `hari_giling` int(10) DEFAULT NULL,
  `tgl_giling` date DEFAULT NULL,
  `thn_giling` varchar(4) DEFAULT NULL,
  `kis` double(10,2) DEFAULT NULL,
  `kis_sd` double(10,2) DEFAULT NULL,
  `kis_inc` double(10,2) DEFAULT NULL,
  `kis_inc_sd` double(10,2) DEFAULT NULL,
  `kes` double(10,2) DEFAULT NULL,
  `kes_sd` double(10,2) DEFAULT NULL,
  `ha_tebang_tr` double(10,3) DEFAULT '0.000',
  `ha_tebang_tr_sd` double(10,3) DEFAULT NULL,
  `ha_tebang_ts` double(10,3) DEFAULT '0.000',
  `ha_tebang_ts_sd` double(10,3) DEFAULT NULL,
  `ha_tebang_ts_saudara` double(10,3) DEFAULT '0.000',
  `ha_tebang_ts_saudara_sd` double(10,3) DEFAULT NULL,
  `ha_tebang_total` double(10,3) DEFAULT '0.000',
  `ha_tebang_total_sd` double(10,3) DEFAULT NULL,
  `ton_tebang_tr` double(10,2) DEFAULT '0.00',
  `ton_tebang_tr_sd` double(10,2) DEFAULT NULL,
  `ton_tebang_ts` double(10,2) DEFAULT '0.00',
  `ton_tebang_ts_sd` double(10,2) DEFAULT NULL,
  `ton_tebang_ts_saudara` double(10,2) DEFAULT '0.00',
  `ton_tebang_ts_saudara_sd` double(10,2) DEFAULT NULL,
  `ton_tebang_total` double(10,2) DEFAULT '0.00',
  `ton_tebang_total_sd` double(10,2) DEFAULT NULL,
  `ha_giling_tr` double(10,3) DEFAULT '0.000',
  `ha_giling_tr_sd` double(10,3) DEFAULT NULL,
  `ha_giling_ts` double(10,3) DEFAULT '0.000',
  `ha_giling_ts_sd` double(10,3) DEFAULT NULL,
  `ha_giling_ts_saudara` double(10,3) DEFAULT '0.000',
  `ha_giling_ts_saudara_sd` double(10,3) DEFAULT NULL,
  `ha_giling_total` double(10,3) DEFAULT '0.000',
  `ha_giling_total_sd` double(10,3) DEFAULT NULL,
  `ton_giling_tr` double(10,2) DEFAULT '0.00',
  `ton_giling_tr_sd` double(10,2) DEFAULT NULL,
  `ton_giling_ts` double(10,2) DEFAULT '0.00',
  `ton_giling_ts_sd` double(10,2) DEFAULT NULL,
  `ton_giling_ts_saudara` double(10,2) DEFAULT '0.00',
  `ton_giling_ts_saudara_sd` double(10,2) DEFAULT NULL,
  `ton_giling_total` double(10,2) DEFAULT '0.00',
  `ton_giling_total_sd` double(10,2) DEFAULT NULL,
  `kristal_tr` double(10,3) DEFAULT '0.000',
  `kristal_tr_sd` double(10,3) DEFAULT NULL,
  `kristal_ts` double(10,3) DEFAULT '0.000',
  `kristal_ts_sd` double(10,3) DEFAULT NULL,
  `kristal_ts_saudara` double(10,3) DEFAULT '0.000',
  `kristal_ts_saudara_sd` double(10,3) DEFAULT NULL,
  `kristal_total` double(10,3) DEFAULT '0.000',
  `kristal_total_sd` double(10,3) DEFAULT NULL,
  `rend_tr` double(10,2) DEFAULT '0.00',
  `rend_tr_sd` double(10,2) DEFAULT NULL,
  `rend_ts` double(10,2) DEFAULT '0.00',
  `rend_ts_sd` double(10,2) DEFAULT NULL,
  `rend_ts_saudara` double(10,2) DEFAULT '0.00',
  `rend_ts_saudara_sd` double(10,2) DEFAULT NULL,
  `rend_total` double(10,2) DEFAULT '0.00',
  `rend_total_sd` double(10,2) DEFAULT NULL,
  `gula_pg_ts` double(10,3) DEFAULT '0.000',
  `gula_pg_ts_sd` double(10,3) DEFAULT NULL,
  `gula_pg_eks_ts_saudara` double(10,3) DEFAULT '0.000',
  `gula_pg_eks_ts_saudara_sd` double(10,3) DEFAULT NULL,
  `gula_pg_eks_tr` double(10,3) DEFAULT '0.000',
  `gula_pg_eks_tr_sd` double(10,3) DEFAULT NULL,
  `gula_pg_total` double(10,3) DEFAULT '0.000',
  `gula_pg_total_sd` double(10,3) DEFAULT NULL,
  `gula_tr_bagihasil` double(10,3) DEFAULT '0.000',
  `gula_tr_bagihasil_sd` double(10,3) DEFAULT NULL,
  `gula_tr_ts_saudara` double(10,3) DEFAULT '0.000',
  `gula_tr_ts_saudara_sd` double(10,3) DEFAULT NULL,
  `gula_produksi` double(10,3) DEFAULT '0.000',
  `gula_produksi_sd` double(10,3) DEFAULT NULL,
  `gula_ex_sisan` double(10,3) DEFAULT '0.000',
  `gula_ex_sisan_sd` double(10,3) DEFAULT NULL,
  `sisan_diolah` double(10,3) DEFAULT '0.000',
  `sisan_diolah_sd` double(10,3) DEFAULT NULL,
  `raw_sugar_diolah` double(10,3) DEFAULT '0.000',
  `raw_sugar_diolah_sd` double(10,3) DEFAULT NULL,
  `gula_repro_thn_lalu` double(10,3) DEFAULT '0.000',
  `gula_repro_thn_lalu_sd` double(10,3) DEFAULT NULL,
  `gula_repro_thn_ini` double(10,3) DEFAULT '0.000',
  `gula_repro_thn_ini_sd` double(10,3) DEFAULT NULL,
  `tetes_produksi` double(10,2) DEFAULT '0.00',
  `tetes_produksi_sd` double(10,2) DEFAULT NULL,
  `tetes_sisan` double(10,2) DEFAULT '0.00',
  `tetes_sisan_sd` double(10,2) DEFAULT NULL,
  `tetes_sto` double(10,2) DEFAULT '0.00',
  `tetes_sto_sd` double(10,2) DEFAULT NULL,
  `tetes_ex_repro` double(10,2) DEFAULT '0.00',
  `tetes_ex_repro_sd` double(10,2) DEFAULT NULL,
  `tetes_total` double(10,2) DEFAULT '0.00',
  `tetes_total_sd` double(10,2) DEFAULT NULL,
  `tebu_terbakar_tr` double(10,2) DEFAULT '0.00',
  `tebu_terbakar_tr_sd` double(10,2) DEFAULT NULL,
  `tebu_terbakar_ts` double(10,2) DEFAULT '0.00',
  `tebu_terbakar_ts_sd` double(10,2) DEFAULT NULL,
  `tebu_terbakar_ts_saudara` double(10,2) DEFAULT '0.00',
  `tebu_terbakar_ts_saudara_sd` double(10,2) DEFAULT NULL,
  `tebu_terbakar_total` double(10,2) DEFAULT '0.00',
  `tebu_terbakar_total_sd` double(10,2) DEFAULT NULL,
  `jam_berhenti_a` double(10,2) DEFAULT '0.00',
  `jam_berhenti_a_sd` double(10,2) DEFAULT NULL,
  `jam_berhenti_b` double(10,2) DEFAULT '0.00',
  `jam_berhenti_b_sd` double(10,2) DEFAULT NULL,
  `total_jb` double(10,2) DEFAULT '0.00',
  `total_jb_sd` double(10,2) DEFAULT NULL,
  `jb_hr` double(10,2) DEFAULT '0.00',
  `jb_hr_sd` double(10,2) DEFAULT NULL,
  `jam_giling` double(10,2) DEFAULT '0.00',
  `jam_giling_sd` double(10,2) DEFAULT NULL,
  `jam_kampanye` double(10,2) DEFAULT '0.00',
  `jam_kampanye_sd` double(10,2) DEFAULT NULL,
  `jam_kampanye_hr` double(10,2) DEFAULT '0.00',
  `jam_kampanye_hr_sd` double(10,2) DEFAULT NULL,
  `jba_persen_jamgil` double(10,3) DEFAULT '0.000',
  `jba_persen_jamgil_sd` double(10,3) DEFAULT NULL,
  `jbb_persen_jamgil` double(10,3) DEFAULT '0.000',
  `jbb_persen_jamgil_sd` double(10,3) DEFAULT NULL,
  `total_persen_jamgil` double(10,3) DEFAULT '0.000',
  `total_persen_jamgil_sd` double(10,3) DEFAULT NULL,
  `ampas_ton` double(10,3) DEFAULT '0.000',
  `ampas_ton_sd` double(10,3) DEFAULT NULL,
  `persen_pol_ampas` double(10,3) DEFAULT '0.000',
  `persen_pol_ampas_sd` double(10,3) DEFAULT NULL,
  `blotong_ton` double(10,3) DEFAULT '0.000',
  `blotong_ton_sd` double(10,3) DEFAULT NULL,
  `persen_pol_blotong` double(10,3) DEFAULT '0.000',
  `persen_pol_blotong_sd` double(10,3) DEFAULT NULL,
  `pol_dlm_hasil_taksasi_ton` double(10,3) DEFAULT '0.000',
  `pol_dlm_hasil_taksasi_ton_sd` double(10,3) DEFAULT NULL,
  `pol_dlm_hasil_taksasi_persenpol` double(10,3) DEFAULT '0.000',
  `pol_dlm_hasil_taksasi_persenpol_sd` double(10,3) DEFAULT NULL,
  `residu` double(10,3) DEFAULT '0.000',
  `residu_sd` double(10,3) DEFAULT NULL,
  `bba_ton` double(10,3) DEFAULT '0.000',
  `bba_ton_sd` double(10,3) DEFAULT NULL,
  `bba_rupiah` double(10,3) DEFAULT '0.000',
  `bba_rupiah_sd` double(10,3) DEFAULT NULL,
  `keterangan_jb` text,
  `icumsa` int(5) DEFAULT NULL,
  `icumsa_sd` int(5) DEFAULT NULL,
  `sbh_tr_sd` double(10,3) DEFAULT '0.000',
  `sbh_tr_ts_saudara_sd` double(10,3) DEFAULT '0.000',
  `sbh_ts_sd` double(10,3) DEFAULT '0.000',
  `sbh_ts_tr_sd` double(10,3) DEFAULT '0.000',
  `sbh_ts_ts_saudara_sd` double(10,3) DEFAULT '0.000',
  `ef_or` double(10,2) DEFAULT '0.00',
  `ef_or_sd` double(10,2) DEFAULT '0.00',
  `status` smallint(1) DEFAULT '1' COMMENT '1. input 2. validasi',
  `tgl_created` datetime DEFAULT NULL,
  `user_created` varchar(100) DEFAULT NULL,
  `tgl_validasi` datetime DEFAULT NULL,
  `user_validasi` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `plant_code` (`plant_code`,`hari_giling`),
  UNIQUE KEY `plant_code_2` (`plant_code`,`tgl_giling`),
  KEY `company_code` (`company_code`,`plant_code`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=latin1;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
